/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerFormaPagamento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.net.URL;
import java.awt.Image;
import java.awt.Toolkit;
import model.ModelFormaPagamento;
import utilidades.Mascaras;

/**
 *
 * @author Jose Luiz
 */
public class PagamentoPdvView extends javax.swing.JDialog {

    ArrayList<ModelFormaPagamento> listaModelFormaPagamento = new ArrayList<>();
    ControllerFormaPagamento controllerFormaPagamento = new ControllerFormaPagamento();
    private float valorTotal;
    private float desconto;
    private float valorRecebido;
    private float troco;
    private String formaPagamento;
    private String pagamento;
    private String parcelasPagamento; // quantidade de parcelas
    private boolean finalizarVenda;
    private int parcelas;
    Mascaras bLMascaras = new Mascaras();

    /**
     * Creates new form ViewPagamentoPDV
     * @param parent
     * @param modal
     */
    public PagamentoPdvView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        URL caminhoImagem = this.getClass().getResource("/icone/pdv.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
        initComponents();
        setLocationRelativeTo(null);
        this.finalizarVenda = false;
        calcularPagamento();
        limparCampos();
        informarFormaPagamento();
        jtfSubtotal.setText("50");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlValorTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfTroco = new javax.swing.JTextField();
        jbOk = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jtfValorRecebido = new javax.swing.JFormattedTextField();
        jtfDesconto = new javax.swing.JFormattedTextField();
        jtfSubtotal = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfFormaPagamento = new javax.swing.JTextField();
        jpParcela = new javax.swing.JPanel();
        jtfParcelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento ");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Total a Pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jlValorTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlValorTotal.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlValorTotal)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel5.setText("Troco:");

        jtfTroco.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtfTroco.setEnabled(false);

        jbOk.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbOk.setText("OK");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        jbOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbOkKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfValorRecebido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfValorRecebidoFocusLost(evt);
            }
        });
        jtfValorRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorRecebidoActionPerformed(evt);
            }
        });
        jPanel3.add(jtfValorRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 138, 335, -1));

        jtfDesconto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescontoFocusLost(evt);
            }
        });
        jtfDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescontoActionPerformed(evt);
            }
        });
        jPanel3.add(jtfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 191, 335, -1));

        jtfSubtotal.setEnabled(false);
        jtfSubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtfSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 335, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Pagamento:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Subtotal:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Desconto:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 198, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Valor Recebido:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, -1, -1));

        jtfFormaPagamento.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtfFormaPagamento.setEnabled(false);
        jtfFormaPagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfFormaPagamentoFocusLost(evt);
            }
        });
        jtfFormaPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFormaPagamentoKeyReleased(evt);
            }
        });
        jPanel3.add(jtfFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 120, -1));

        jpParcela.setBackground(new java.awt.Color(153, 255, 204));
        jpParcela.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpParcela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfParcelas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfParcelas.setEnabled(false);
        jtfParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfParcelasActionPerformed(evt);
            }
        });
        jpParcela.add(jtfParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 132, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Parcelas");
        jpParcela.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("X");
        jpParcela.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel3.add(jpParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 210, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        salvarVenda();
    }//GEN-LAST:event_jbOkActionPerformed

    private void jtfDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescontoFocusLost
        jtfDesconto.setText(bLMascaras.converterVirgulaParaPonto(jtfDesconto.getText()));
        calcularPagamento();
    }//GEN-LAST:event_jtfDescontoFocusLost

    private void jtfValorRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfValorRecebidoFocusLost
        jtfValorRecebido.setText(bLMascaras.converterVirgulaParaPonto(jtfValorRecebido.getText()));
        calcularPagamento();
        calcularTroco();
    }//GEN-LAST:event_jtfValorRecebidoFocusLost

    private void jtfDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescontoActionPerformed
        jbOk.requestFocus();
    }//GEN-LAST:event_jtfDescontoActionPerformed

    private void jtfValorRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorRecebidoActionPerformed
        jtfDesconto.requestFocus();
    }//GEN-LAST:event_jtfValorRecebidoActionPerformed

    private void jbOkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbOkKeyReleased
        salvarVenda();
    }//GEN-LAST:event_jbOkKeyReleased

    private void jtfFormaPagamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFormaPagamentoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfFormaPagamentoFocusLost

    private void jtfFormaPagamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFormaPagamentoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfFormaPagamentoKeyReleased

    private void jtfParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfParcelasActionPerformed
        // TODO add your handling code here:
        jtfValorRecebido.requestFocus();
    }//GEN-LAST:event_jtfParcelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagamentoPdvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagamentoPdvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagamentoPdvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagamentoPdvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            PagamentoPdvView dialog = new PagamentoPdvView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public void setTextFieldValorTotal() {
        this.jtfSubtotal.setText(String.valueOf(valorTotal));
    }

    private void calcularPagamento() {
        float subTotal, desconto, recebido, pagar;

        try {
            subTotal = Float.parseFloat(jtfSubtotal.getText());
        } catch (NumberFormatException e) {
            subTotal = 0;
        }
        try {
            desconto = Float.parseFloat(jtfDesconto.getText());
        } catch (NumberFormatException e) {
            desconto = 0;
            jtfDesconto.setText("");
        }
        try {
            recebido = Float.parseFloat(jtfValorRecebido.getText());
        } catch (NumberFormatException e) {
            recebido = 0;
            jtfValorRecebido.setText("");
        }
        //calcular o valor a pagar
        if ("CARTÃO".equals(jtfFormaPagamento.getText())) {
            setParcelas(Integer.parseInt(jtfParcelas.getText()));
            pagar = (subTotal - desconto) / getParcelas();
            jlValorTotal.setText(bLMascaras.arredondamentoComPontoDuasCasasString(pagar));
        } else {
            pagar = subTotal - desconto;
            jlValorTotal.setText(bLMascaras.arredondamentoComPontoDuasCasasString(pagar));
        }
    }

    private void calcularTroco() {
        float subTotal, desconto, recebido, pagar, troco;

        try {
            subTotal = Float.parseFloat(jtfSubtotal.getText());
        } catch (NumberFormatException e) {
            subTotal = 0;
        }
        try {
            desconto = Float.parseFloat(jtfDesconto.getText());
        } catch (Exception e) {
            desconto = 0;
            jtfDesconto.setText("");
        }
        try {
            recebido = Float.parseFloat(jtfValorRecebido.getText());
        } catch (Exception e) {
            recebido = 0;
            jtfValorRecebido.setText("");
        }
        //calcular o valor a pagar
        pagar = subTotal - desconto;
        jlValorTotal.setText(bLMascaras.arredondamentoComPontoDuasCasasString(pagar));

        //calcula o troco
        troco = recebido - pagar;
        jtfTroco.setText(bLMascaras.arredondamentoComPontoDuasCasasString(troco));
    }

    private void salvarVenda() {
        this.desconto = Float.parseFloat(this.jtfDesconto.getText());
        this.valorRecebido = Float.parseFloat(this.jtfValorRecebido.getText());
        this.troco = Float.parseFloat(this.jtfTroco.getText());
        this.valorTotal = Float.parseFloat(this.jlValorTotal.getText());
        this.formaPagamento = (this.jtfFormaPagamento.getText());
        this.setParcelasPagamento(String.valueOf(this.getParcelas()));
        JOptionPane.showMessageDialog(this, "Venda Finalizada com Sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        this.finalizarVenda = true;
        limparCampos();
        dispose();
    }

    private void limparCampos() {
        jtfSubtotal.setText("");
        jtfDesconto.setText("");
        jtfValorRecebido.setText("");
        jlValorTotal.setText("0");
        jtfTroco.setText("");
        jtfFormaPagamento.setText("");
        jtfParcelas.setText("");
    }

    private void informarFormaPagamento() {
        formaPagamento = JOptionPane.showInputDialog(this, "Qual a forma de pagamento?\n"
                + "1. A Vista\n"
                + "2. Cartão", "Atenção", JOptionPane.WARNING_MESSAGE);

        if ("1".equals(formaPagamento)) {
            this.setPagamento("A VISTA");
            this.setParcelasPagamento("1");
            jtfParcelas.setEnabled(false);
        } else if ("2".equals(formaPagamento)) {
            this.setParcelasPagamento(String.valueOf(this.getParcelas()));
            this.setPagamento("CARTÃO");
            jtfParcelas.setEnabled(true);
            jtfParcelas.requestFocusInWindow();
        }
        jtfFormaPagamento.setText(this.getPagamento());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlValorTotal;
    private javax.swing.JPanel jpParcela;
    private javax.swing.JFormattedTextField jtfDesconto;
    private javax.swing.JTextField jtfFormaPagamento;
    private javax.swing.JTextField jtfParcelas;
    private javax.swing.JFormattedTextField jtfSubtotal;
    private javax.swing.JTextField jtfTroco;
    private javax.swing.JFormattedTextField jtfValorRecebido;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the valorTotal
     */
    public float getValorTotal() {
        return valorTotal;
    }

    /**
     * @param valorTotal the valorTotal to set
     */
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

    /**
     * @return the desconto
     */
    public float getDesconto() {
        return desconto;
    }

    /**
     * @param desconto the desconto to set
     */
    public void setDesconto(float desconto) {
        this.desconto = desconto;
    }

    /**
     * @return the valorRecebido
     */
    public float getValorRecebido() {
        return valorRecebido;
    }

    /**
     * @param valorRecebido the valorRecebido to set
     */
    public void setValorRecebido(float valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    /**
     * @return the troco
     */
    public float getTroco() {
        return troco;
    }

    /**
     * @param troco the troco to set
     */
    public void setTroco(float troco) {
        this.troco = troco;
    }

    /**
     * @return the formaPagamento
     */
    public String getFormaPagamento() {
        return formaPagamento;
    }

    /**
     * @param formaPagamento the formaPagamento to set
     */
    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    /**
     * @return the finalizarVenda
     */
    public boolean isFinalizarVenda() {
        return finalizarVenda;
    }

    /**
     * @param finalizarVenda the finalizarVenda to set
     */
    public void setFinalizarVenda(boolean finalizarVenda) {
        this.finalizarVenda = finalizarVenda;
    }

    public void setPagamento(String pagamento) {
        this.pagamento = pagamento;
    }

    public String getPagamento() {
        return pagamento;
    }

    /**
     * @return the parcelasPagamento
     */
    public String getParcelasPagamento() {
        return parcelasPagamento;
    }

    /**
     * @param parcelasPagamento the parcelasPagamento to set
     */
    public void setParcelasPagamento(String tipoPagamento) {
        this.parcelasPagamento = tipoPagamento;
    }

    /**
     * @return the parcelas
     */
    public int getParcelas() {
        return parcelas;
    }

    /**
     * @param parcelas the parcelas to set
     */
    public void setParcelas(int parcelas) {
        this.parcelas = parcelas;
    }
}
